import { Crown, Sparkles, Zap } from "lucide-react";
import type { Plan } from "./types";

export const INDUSTRY_OPTIONS = [
  "Any Industry",
  "Accounting / Auditing / Taxation",
  "Agriculture / Forestry / Livestock / Fertilizers",
  "Airlines / Aviation / Aerospace",
  "Automobile/Auto-Components",
  "Banking, Financial Services & Insurance",
  "Beverage / Brewery / Distillery",
  "Chemical Manufacturing",
  "Consumer Goods & Retail",
  "Design",
  "Education",
  "Emerging Technologies",
  "Energy & Power",
  "Gold, Gems, Watches, Jewellery & Accessories",
  "Government / Public Administration",
  "HR, Recruitment & Staffing",
  "Hospitality, Travel & Tourism",
  "Hospitals, Health Care & Lifescience",
  "IT Services, Software, Internet & Computers",
  "Infrastructure & Transport",
  "Legal & Regulatory",
  "Logistics, Trade & Commerce",
  "Manufacturing & Production",
  "Media, Advertising, PR & Marketing",
  "Media, Film & Entertainment",
  "Metals & Mining",
  "NGO / Social Services / Industry Associations",
  "Outsourcing - BPO/BPM",
  "Professional Services & Consulting",
  "Real Estate & Facility Management",
  "Textile, Handicraft & Fashion",
];

export const JOB_CATEGORIES = [
  "IT & Software",
  "Sales & Marketing",
  "Design & Creative",
  "Writing & Content",
  "Admin & Customer Support",
  "Finance & Accounting",
  "Education & Training",
  "Healthcare",
  "Construction & Real Estate",
  "Manufacturing & Operations",
  "Others",
];

export const DEGREE_OPTIONS = [
  "All degree",
  "Diploma",
  "Advanced Diploma",
  "Advanced Diploma in Computer Applications",
  "Auxiliary Nurse Midwife",
  "Diploma in Chemical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Computer Applications",
  "Diploma in Computer Engineering",
  "Diploma in Computer Science and Engineering",
  "Diploma in Education",
  "Diploma in Electrical and Electronics Engineering",
  "Diploma in Electronics Engineering",
  "Diploma in Elementary Education",
  "Diploma in Hotel Management",
  "Diploma in Information Technology",
  "Diploma in Mechanical Engineering",
  "Diploma in Medical Laboratory Technology",
  "Diploma in Nursing",
  "Diploma in Physiotherapy",
  "D.Pharma",
  "General Nursing and Midwifery",
  "Polytechnic Diploma",
  "ITI",
  "Graduate",
  "B.A",
  "Bachelor",
  "Bachelor of Agriculture",
  "Bachelor of Aircraft Maintenance Engineering",
  "Bachelor of Arts in Journalism and Mass Communication",
  "Bachelor of Arts in Mass Media and Communication",
  "Bachelor of Aviation",
  "Bachelor of Banking and Insurance",
  "Bachelor of Economics",
  "Bachelor of Elementary Education",
  "Bachelor of Financial Management",
  "Bachelor of Hotel Management and Catering Technology",
  "Bachelor of Interior Design",
  "Bachelor of Journalism and Mass Communication",
  "Bachelor of Library and Information Science",
  "Bachelor of Mass Media",
  "Bachelor of Medical Laboratory Technology",
  "Bachelor of Naturopathy and Yogic Sciences",
  "Bachelor of Physical Education",
  "Bachelor of Physiotherapy",
  "Bachelor of Rural Studies",
  "Bachelor of Science in Agriculture",
  "Bachelor of Science in Nursing",
  "Bachelor of Social Work",
  "Bachelor of Tourism Studies",
  "Bachelor of Travel and Tourism Management",
  "Bachelor of Unani Medicine and Surgery",
  "Bachelor of Visual Arts",
  "BAF",
  "B.A (Hons.)",
  "BAMS",
  "B.Arch",
  "BASc",
  "BBA",
  "BBA (Hons.)",
  "BBE",
  "BBM",
  "BBM (Hons.)",
  "BCA",
  "B.Com",
  "B.Com (Hons.)",
  "B.Design",
  "BDS",
  "BE/B.Tech",
  "B.Ed",
  "BFA",
  "B.FTech",
  "BHM",
  "BHMS",
  "BMS",
  "BPA",
  "B.Pharm",
  "B.Pharm (Hons.)",
  "B.Sc",
  "B.Sc (Hons.)",
  "B.Voc",
  "LLB",
  "LLB (Hons.)",
  "MBBS",
  "Pharm.D",
  "Post Graduate",
  "Chartered Accountant (CA)",
  "CS",
  "DM",
  "Doctor of Education",
  "Dual Degree (BE/B.Tech + ME/ M.Tech)",
  "ICWA (CMA)",
  "LLM",
  "M.A",
  "M.A (Hons.)",
  "M.Arch",
  "Master",
  "Master of Computer Management",
  "Master of Dental Surgery",
  "Master of Health Administration",
  "Master of Hospital Administration",
  "Master of Human Resource Management",
  "Master of Journalism and Mass Communication",
  "Master of Library and Information Science",
  "Master of Library Science",
  "Master of Management Studies",
  "Master of Physical Education",
  "Master of Physical Therapy",
  "Master of Physiotherapy",
  "Master of Psychology",
  "Master of Public Administration",
  "Master of Social Work",
  "Master of Tourism and Travel Management",
  "MBA",
  "MBA(executive)",
  "MCA",
  "MCh",
  "M.Com",
  "MD",
  "M.Des",
  "M.Ed",
  "ME/M.Tech",
  "MFA",
  "M.Mus.",
  "M.Pharm",
  "M.Phil",
  "M.Plan",
  "M.Sc",
  "M.Voc",
  "PG Diploma",
  "PGDM",
  "PGP",
  "PhD",
  "Post Graduate Diploma in Banking",
];

export const REGIONAL_LANGUAGES = [
  "Assamese",
  "Bengali",
  "Gujarati",
  "Hindi",
  "Malayalam",
  "Kannada",
  "Marathi",
  "Oriya",
  "Punjabi",
  "Tamil",
  "Telugu",
  "English",
];

export const WALK_IN_START_TIMES = [
  "8:00 AM",
  "8:30 AM",
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
];

export const WALK_IN_END_TIMES = [
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
];

export const PERK_OPTIONS = [
  "Flexible Working Hours",
  "Weekly Payout",
  "Overtime Pay",
  "Joining Bonus",
  "Annual Bonus",
  "PF",
  "Travel Allowance (TA)",
  "Petrol Allowance",
  "Mobile Allowance",
  "Internet Allowance",
  "Laptop",
  "Health Insurance",
  "ESI (ESIC)",
  "Food/Meals",
  "Accommodation",
  "5 Working Days",
  "One-Way Cab",
  "Two-Way Cab",
];

export const STEPS = [
  { id: 1, label: "Identity" },
  { id: 2, label: "Narrative" },
  { id: 3, label: "Logistics" },
  { id: 4, label: "Review" },
];

export const plans: Plan[] = [
  {
    id: "basic",
    name: "Classic",
    price: "0",
    icon: <Zap className="size-5" />,
    aiAgent: false,
    features: [
      "Standard job posting",
      "Active for 30 days",
      "Basic candidate filtering",
    ],
  },
  {
    id: "pro",
    name: "Accelerate",
    price: "1,499",
    icon: <Sparkles className="size-5" />,
    aiAgent: true,
    badge: "Most Popular",
    popular: true,
    features: [
      "Priority in search results",
      "Whatsapp application alerts",
      "Verified badge",
      "AI Candidate matching",
    ],
  },
  {
    id: "enterprise",
    name: "Dominance",
    price: "4,999",
    icon: <Crown className="size-5" />,
    aiAgent: true,
    features: [
      "Premium placement",
      "Unlimited candidate unlocks",
      "Dedicated account manager",
      "Bulk resume export",
    ],
  },
];
